### ISSUE TITLE
Extend Base.zero to easily initialize empty `Qobj`

### ISSUE THREAD

**Issue by labay11** [qutip/QuantumToolbox.jl#342]
### Problem Description

The `zero_ket` function already exists, but this is more general and allows the initialization of an empty object of the same type and dims of other objects. Useful, for instance, for `reduce` or other Julia functions. 

### Proposed Solution

```julia
Base.zero(x::AbstractQuantumObject) = QuantumObject(zero(x.data), dims=x.dims, type=x.type)
```

**Comment by ytdHuang** [comment]
I think it's a good idea since this is a standard `julia` implementation.

For `Base.zero(A::QuantumObject)`, I agree.

I'm not sure what should we do for `QobjEvo`, because `SciMLOperators.jl` also supports this functionality:

```julia
julia> zero(MatrixOperator([1 2; 3 4]))
NullOperator(2)
```

I don't know what can we do with this `NullOperator` ...

But I think it would be better to still

```julia
Base.zero(A::QuantumObjectEvolution) = QuantumObjectEvolution(zero(A.data), dims=A.dims, type=A.type)
```

to avoid ambiguity ?

If this is the case, then we can simply define the function as:

```julia
Base.zero(A::AbstractQuantumObject) = get_typename_wrapper(A)(zero(A.data), dims=A.dims, type=A.type)
```

**Comment by ytdHuang** [comment]
@albertomercurio 

Any comments ?

**Comment by albertomercurio** [comment]
I think it's a good idea. We can use the simplest definition for both constant and time dependent case. I don't see an easy definition for SciMLOperators, and maybe one should make a PR there for that specific case.

**Comment by ytdHuang** [comment]
> I think it's a good idea. We can use the simplest definition for both constant and time dependent case. I don't see an easy definition for SciMLOperators, and maybe one should make a PR there for that specific case.

So you prefer the last implementation I mentioned ?

**Comment by albertomercurio** [comment]
Yes I would say.
